services:
  dnd-battle-database:
    container_name: 'dnd-battle-database'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dnd-database'
      - 'POSTGRES_PASSWORD=dnd-secret'
      - 'POSTGRES_USER=dnd-user'
    ports:
      - '5432'
    networks:
      - dnd-battle-network
  dnd-battle-pgadmin:
    container_name: 'dnd-battle-pgadmin'
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=developer.gubler@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=letmein'
      - 'PGADMIN_LISTEN_PORT=5050'
    ports:
      - '5051:5050'
    networks:
      - dnd-battle-network
    depends_on:
      - dnd-battle-database
  dnd-battle:
    container_name: dnd-battle
    build:
      context: .
      dockerfile: Dockerfile
    image: dnd-battle:latest
    ports:
      - 8081:8080
    networks:
      - dnd-battle-network
    depends_on:
        - dnd-battle-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dnd-battle-database:5432/dnd-database
      - SPRING_DATASOURCE_USERNAME=dnd-user
      - SPRING_DATASOURCE_PASSWORD=dnd-secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
networks:
  dnd-battle-network:
    driver: bridge